name: build and publish docker image artificats
on:
  push:
    branches:
      - main

env:
  VERSION: 'temp'      

jobs:
  build-upload-docker-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          fetch-depth: '2'
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: build and push image to DockerHub
        run: |
          docker build -t docker.io/krishna3780/supermario:${{env.VERSION}} .
          docker push docker.io/krishna3780/supermario:${{env.VERSION}} 
      - name: list the current dir
        run: |
          pwd
          ls -l
          sudo find / -name 'supermario'
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: .        