name: first-workflow
on:
  schedule:
   - cron: "* * * * *"
  push:
    branches:
      - main
  workflow_dispatch:


 
env:
  workflowname: first-workflow
     
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello world
        run: |
          echo "${{env.workflowname}}"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: |
          echo "Myself Krishna"
          echo "${{toJSON(github)}}"
          echo "${{toJSON(secrets)}}"
          echo "${{secrets.github_token}}"
          echo "for dummy commit"
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: Github context objects
        run: |
          echo "${{toJSON(env)}}" 
          echo "${{toJSON(runner)}}"
          echo "${{toJSON(needs)}}"       
