name: Explore context objects (github)
on:
  push:
    branches:
      - main

env:
  name: krishna
jobs:
  context-data:
    runs-on: ubuntu-latest
    if: ${{ github.event_name=='push' }}
    steps:
      # - name: print github context object
      #   run: |
      #     echo '${{ toJSON(github) }}'
      #     echo "#########################"
      #     echo "${{ github.event_name }}"
      - name: print env context
        run: |
          echo "${{ env.name }}"
          echo '${{ toJSON(env) }}'   
          