name: Explore context objects (github)
on:
  push:
    branches:
      - main

jobs:
  context-data:
    runs-on: ubuntu-latest
    if: ${{ github.event_name=='push' }}
    steps:
      - name: print github context object
        run: |
          echo '${{ toJSON(github) }}'
          echo "#########################"
          echo "${{ github.event_name }}"