name: Explore context objects (github)
on:
  push:
    branches:
      - main

env:
  env-var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    runs-on: ${{ vars.RUNNER }}
    if: ${{ github.event_name=='push' }}
    steps:
      # - name: print github context object
      #   run: |
      #     echo '${{ toJSON(github) }}'
      #     echo "#########################"
      #     echo "${{ github.event_name }}"
      # - name: print env context
      #   run: |
      #     echo "${{ env.name }}"
      #     echo '${{ toJSON(env) }}'
      - name: Use Variables
        run: |
          #echo 'repo varaiable: ${{ REPO_VAR }}'
          echo "hello"
    


          