
name: Explore context objects (github)

on:
  push:
    branches:
      - main

env:
  env-var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    runs-on: ${{ vars.RUNNER }} # Ensure this is defined in repo variables
    if: ${{ github.event_name == 'push' }}
    steps:
      # - name: Print GitHub context object
      #   run: |
      #     echo '${{ toJSON(github) }}'
      #     echo "#########################"
      #     echo "${{ github.event_name }}"

      # - name: Print env context
      #   run: |
      #     echo "env.name: ${{ env.env-var }}"
      #     echo '${{ toJSON(env) }}'

      - name: Use Variables
        run: |
          echo "Repo variable: ${{ vars.REPO_VAR }}"
          echo "Hello"
