name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{runner.os}}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Build with logs
        run: |
          mkdir ${{runner.temp}}/build_logs
          echo "Logs from building" > ${{runner.temp}}/build_logs/build.log
          # exit 1
      - name: upload logs on fail
        uses: actions/upload-artifact@v4
        with:
          name: build failure logs
          path: ${{runner.temp}}/build_logs  