name: Open new issue
on: [ push,workflow_dispatch ]

jobs:
  Open_issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Create issue
        run: |
          gh issue --repo ${{github.repository}} create --title "issue title" --body "issue body"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    