name: Generate random number
on:
  worflow_dispatch:
    branches:
      - main

jobs:
  Generate_Random:
    runs-on: ubuntu-latest
    steps:
      - name: Generate number
        id: generate_number
        run: |
          echo "$RANDOM"
          echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
      - name: Pass or Fail
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1; fi    

